
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 13 16:56:14 CEST 2013
//----------------------------------------------------

package plg.pruebas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTS = 11;
  public static final int CONST = 15;
  public static final int CHAR = 27;
  public static final int INSTRUCTIONS = 13;
  public static final int SUBPROGRAM = 9;
  public static final int VARS = 10;
  public static final int NATURAL = 22;
  public static final int MENOIG = 46;
  public static final int INTEGER = 21;
  public static final int FLLAVE = 40;
  public static final int INT = 25;
  public static final int OUT = 17;
  public static final int LITFLOAT = 4;
  public static final int NOIGUAL = 49;
  public static final int CHARACTER = 23;
  public static final int NOT = 57;
  public static final int AND = 55;
  public static final int IGUAL = 48;
  public static final int RPAR = 38;
  public static final int LSH = 58;
  public static final int OR = 56;
  public static final int IN = 16;
  public static final int DIV = 53;
  public static final int IF = 28;
  public static final int ENDWHILE = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 24;
  public static final int ASIG = 35;
  public static final int TRUE = 6;
  public static final int error = 1;
  public static final int PROGRAM = 8;
  public static final int MUL = 52;
  public static final int COMA = 42;
  public static final int MENOS = 51;
  public static final int MOD = 54;
  public static final int LITNAT = 3;
  public static final int IDENT = 2;
  public static final int RSH = 59;
  public static final int BARRABAJA = 43;
  public static final int ENDIF = 31;
  public static final int ELSE = 30;
  public static final int MEN = 44;
  public static final int ILLAVE = 39;
  public static final int WHILE = 32;
  public static final int MAYOIG = 47;
  public static final int DPIGUAL = 36;
  public static final int FLOAT = 20;
  public static final int THEN = 29;
  public static final int SWAP2 = 19;
  public static final int SWAP1 = 18;
  public static final int LPAR = 37;
  public static final int NAT = 26;
  public static final int FALSE = 7;
  public static final int MAY = 45;
  public static final int VAR = 14;
  public static final int SUBPROGRAMS = 12;
  public static final int LITCHAR = 5;
  public static final int DO = 33;
  public static final int PYC = 41;
  public static final int MAS = 50;
}

